template: python
runtime: python:3.8.6-buster

env:
  - name: APP_NAME
    value: "Flask-Example"
    
entrypoint:
  - pip install -r requirements.txt
  - gunicorn --bind=0.0.0.0 --workers=4 startup:app
